sudo: required
services: docker
language: generic

env:
    global:
        - DOCKER_ENGINE_VERSION=1.12.2

before_install:
    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_ENGINE_VERSION}-0~trusty
    - docker-compose --version

script:
    - docker pull cyberdojofoundation/gcc_assert
    - docker pull cyberdojofoundation/java_cucumber_pico
    - docker pull cyberdojofoundation/csharp_moq
    - docker pull cyberdojofoundation/csharp_nunit
    - ./build.sh
    - ./up.sh
    - sleep 2
    - ./test.sh

after_success:
    - if [ "${TRAVIS_BRANCH}" == "master" ]; then
        docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}";
        docker push cyberdojo/runner;
      fi
