sudo: required
services: docker
language: node_js

before_script:
    - curl -O https://raw.githubusercontent.com/cyber-dojo/ruby/master/push_and_trigger.sh
    - chmod +x push_and_trigger.sh

script:
    # pull images used by tests
    - docker pull cyberdojofoundation/gcc_assert
    - docker pull cyberdojofoundation/java_cucumber_pico
    - docker pull cyberdojofoundation/csharp_moq
    - docker pull cyberdojofoundation/csharp_nunit
    - docker pull cyberdojofoundation/clangpp_assert
    #
    - ./pipe_build_up_test.sh
    - status=$?
    - ./push_and_trigger.sh ${status} cyber-dojo/web
