sudo: required
services: docker
language: generic

script:
    - curl -O https://raw.githubusercontent.com/cyber-dojo/ruby/master/push.sh
    - chmod +x push.sh

    - docker pull cyberdojofoundation/gcc_assert
    - docker pull cyberdojofoundation/java_cucumber_pico
    - docker pull cyberdojofoundation/csharp_moq
    - docker pull cyberdojofoundation/csharp_nunit

    - ./pipe_build_up_test.sh

    - ./push.sh
