sudo: required
services: docker
language: generic

env:
    global:
        - DOCKER_ENGINE_VERSION=1.12.2

before_install:
    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_ENGINE_VERSION}-0~trusty
    - docker-compose --version

script:
    - docker pull cyberdojofoundation/gcc_assert
    - docker pull cyberdojofoundation/ruby_mini_test
    - docker pull cyberdojofoundation/fsharp_nunit
    - docker pull cyberdojofoundation/csharp_nunit
    - ./build.up
    - ./up.sh
    - sleep 2
    - ./test.sh

after_success:
    - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
    - docker push cyberdojo/runner:${DOCKER_ENGINE_VERSION}

