sudo: required
services: docker
language: node_js

script:
    # pull images used by tests
    - docker pull cyberdojofoundation/gcc_assert
    - docker pull cyberdojofoundation/java_cucumber_pico
    - docker pull cyberdojofoundation/csharp_moq
    - docker pull cyberdojofoundation/csharp_nunit
    - docker pull cyberdojofoundation/clangpp_assert
    # go!
    - ./pipe_build_up_test.sh
    # success!
    - curl -O https://raw.githubusercontent.com/cyber-dojo/ruby/master/push_and_trigger.sh
    - chmod +x push_and_trigger.sh
    - ./push_and_trigger.sh cyber-dojo/web
