sudo: required
services: docker
language: generic

env:
    global:
        - DOCKER_ENGINE_VERSION=1.12.2

before_install:
    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_ENGINE_VERSION}-0~trusty
    - docker-compose --version

script:
    - docker pull cyberdojofoundation/gcc_assert
    - docker pull cyberdojofoundation/java_cucumber_pico
    - docker pull cyberdojofoundation/csharp_moq
    - docker pull cyberdojofoundation/csharp_nunit
    - ./build.sh
    - ./up.sh
    - ./test.sh
    - curl -O https://raw.githubusercontent.com/cyber-dojo/ruby/master/push.sh
    - chmod +x push.sh
    - ./push.sh
