
version: '2'

services:
  runner_client:
    user: nobody
    image: cyberdojo/runner_client
    build:
      context: client
      args:
        PORT: 4558
    ports: [ "4558:4558" ]
    container_name: runner_client

  runner:
    build:
      context: server
      args:
        PORT: 4557
    image: cyberdojo/runner
    container_name: runner_server
    environment: [ CYBER_DOJO_RUNNER_CLASS ]
    user: root
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
