
version: '2'

services:
  runner_client:
    user: nobody
    image: cyberdojo/runner_client
    container_name: runner_client
    command: [ "foreman", "start", "-d", "/app" ]
    links: [ runner_server ]

  runner_server:
    user: cyber-dojo
    image: cyberdojo/runner:${DOCKER_ENGINE_VERSION}
    container_name: runner_server
    command: [ "foreman", "start", "-d", "/app" ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

